### ISSUE TITLE
How about a 8080-based CPC?

### ISSUE THREAD

**Issue by cpcitor** [Bread80/CPC_ZERO#1]
Hi. I've read that most of the ROM of the CPC was made from what Locomotive Software wrote for the 8080.

From reading ROM disassembly, indeed most of the code does not use Z80-specific instructions. For example, IX and IY are (mostly?) not modified by firmware.

The interrupt handler does use Z80-specific code, actually alternate B and C registers IIRC.

It would be interesting to run a CPC-compatible computer using a real Intel 8080. It would require some adjustments to the few parts of the ROM that are actually Z80-specific to make then 8080-compatible. Just an idea.

**Comment by Bread80** [comment]
Hi,
I'm not sure I'd agree with that the firmware avoids Z80 instructions.
My page at  <https://bread80.com/2022/07/09/comparing-datapoint-2200-
8008-8080-and-z80-instruction-sets/> has a table, near the end of the
article, which shows where all of the instructions in the 'base' page
originated. This includes the JR and DJNZ relative jumps which the
firmware make heavy use of.

IY is used by a variety of low jumpblock routines, as well as by RSX
calls. Other than that I'd argue they're avoided because they're slow to
use. They would argue that IX and the alternate registers are left free
for user code to use.

As to other instructions, the upper jumpblock code makes heavy use of
the bit test, set and reset instructions in it's ROM selection code.
There are plenty of LDIR etc block instructions in use, as well as CB
shifts and rotates.

My understanding of the history of the firmware is that the BASIC was
written for the BBC Micros Z80 co-processor, and the remainder was
custom for the Amstrad. I've not seen anything which suggests it dates
back to the 8080.


Having said that, of course, backporting the firmware to an 8080 might
be an interesting exercise. I've never worked with an 8080 at the
hardware level, but since the 8080 instruction set is a subset of Z80 an
8080 based firmware would run fine on existing hardware.

As for whether I'd be interested in such a project then I'd respond with
a firm no. The firmware would be a huge project and I have plenty of
projects that I'd much rather work on.

Mike

On December 26, 2024, Adrian Chadd ***@***.***> wrote:
> Hi. I've read that most of the ROM of the CPC was made from what
> Locomotive Software wrote for the 8080.
>
> From reading ROM disassembly, indeed most of the code does not use
> Z80-specific instructions. For example, IX and IY are (mostly?) not
> modified by firmware.
>
> The interrupt handler does use Z80-specific code, actually B and C
> registers IIRC.
>
> It would be interesting to run a CPC-compatible computer using a real
> Intel 8080. It would require some adjustments to the few parts that
> are actually Z80-specific to make then 8080-compatible. Just an idea.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/Bread80/CPC_ZERO/issues/1>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AQANIYCL6QRUNB36GRFANVL2HR5NVAVCNFSM6AAAAABUHX6TO2VHI2DSMVQWIX3LMV43ASLTON2WKOZSG43DAMJYGI2DIOI>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by cpcitor** [comment]
Initially it seemed less outlandish to run a CPC on a 8080 than a 6502 because "it's closer" but while true this is not what this is about here (the original and doomed 6502-based design for the CPC).
Thanks for this analysis, rooted in an extensive knowledge of the firmware and its historical context.
Thanks for your interesting blog also.
